### ISSUE TITLE
Some ideas.

### ISSUE THREAD

**Issue by CGNefarious** [JohN100x1/WOTR_IsekaiMod#104]
Really love this mod, and I'm glad to see that you're still working on it regularly. I thought I'd throw out some ideas that might be able to improve it. If you like any of them, I can try to develop them further, but for now they are just concepts.

1. Isekai Human - Try to play up the human versatility. +2 to all stats, extra skill points and hit points every level, and maybe they also get access to an extra special power or overpowered ability at first level in addition to the bonus feat?
2. Option to prevent non-IPs from selecting Exceptional Feats or the Overpowered Ability/Special Power Mythic Abilities. Make the IP feel more special.
3. Maybe a Special Isekai Protagonist Mythic Class. I'm assuming adding entirely new mythic classes is not possible currently (seeing as how nobody has done it yet) but modifying an existing Mythic Class should be possible. Bonus points if it gets access to all mythic quests (or at least a subset that makes sense).
4. The ability to force Wendu and Lan to join the party in Act I. You're the freaking main character. If you want both of these irreconcilable personalities to join your party and work together, the mangaka will find a way to make it happen.
5. Special Power to be able to use any equipment regardless of alignment/class/etc.
6. Additional class specific interactions. I'll have to think on this one. Maybe getting Hulrun and Ramien to play nice. Extra taunts to Minago/Nulkineth/etc.
7. I'm sure this one will be a bit controversial, but a more balanced version of the class. Or perhaps I should say less overpowered. Grim Dark Isekai Protagonist or something to make it clear there are some stakes and he might actually have to struggle a bit. This would be a lot of work too, but it'd mostly be tuning down most of the abilities and locking some of the more extreme overpowered abilities at higher levels.

That's all I got for now. I'm sure there are some low hanging fruit additions too, like additional races and special powers/overpowered abilities that could be added fairly easily. If you like any of these and want to me expand upon them more, let me know. If you think they are trash or untenable, then feel free to ignore them.

**Comment by kjk001** [comment]
1. We need at least 2-3 human options to make it worth to implement human heritages, so please make a few more suggestions if you want to see that feature.
2. Overpowered Abilities and Special Powers should already only be available to the IP and its archetypes, only the exceptional feats are available to companions. If you found a way to get an Overpowered Feat on a non IP Archetype please report more details so we can find where the game broke.
3. Mythic Classes themself are easy, they are basically just normal class definitions. Its all the dialogue/questchains/special events/triggers that check what your mystical class is that kill any attempt as you would have to touch the code of half of each campaign to add your option in. There is a reason why owlcat themself are not providing the vampire option so many would prefer to that stupid lich...
4. That should be feasible. It is similiar to several triggers that John already programmed. I like the idea, give them a "Shut up, both your points are invalid because they will just lead to destroying your kind in a different way. You need to meet in the middle to survive." @JohN100x1 What do you think?
5. I'm not sure if you can set a flag to ignore such flags on everything.
6. John has already added several places where you get special dialogue. If you want more of them please make specific suggestions, where, what text, what result... Not making a promise they will all be implemented but that will at least tell us what places to think about.
7. If you want to see additional archetypes, even a less overpowered one for a harder run through be specific with your suggestion: name, description, general outline of what feature is gained at what level...

**Comment by JohN100x1** [comment]
>> 1. Isekai Human - Try to play up the human versatility. +2 to all stats, extra skill points and hit points every level, and maybe they also get access to an extra special power or overpowered ability at first level in addition to the bonus feat?
> 1. We need at least 2-3 human options to make it worth to implement human heritages, so please make a few more suggestions if you want to see that feature.

I think one option is enough. The only problem with implementation is maybe making the heritage selection appear since humans don't have a heritage selection by default.

>> 2. Option to prevent non-IPs from selecting Exceptional Feats or the Overpowered Ability/Special Power Mythic Abilities. Make the IP feel more special.
> 2. Overpowered Abilities and Special Powers should already only be available to the IP and its archetypes, only the exceptional feats are available to companions. If you found a way to get an Overpowered Feat on a non IP Archetype please report more details so we can find where the game broke.

This used to be the case but not anymore... because some users wanted OP abilities and special powers in the Mythic ability selection I made it accessible to non IP classes. The solution here should be to add a settings option in UMM to decide whether to exclude non IP classes from selecting these.

>> 3. Maybe a Special Isekai Protagonist Mythic Class. I'm assuming adding entirely new mythic classes is not possible currently (seeing as how nobody has done it yet) but modifying an existing Mythic Class should be possible. Bonus points if it gets access to all mythic quests (or at least a subset that makes sense).
> 3. Mythic Classes themself are easy, they are basically just normal class definitions. Its all the dialogue/questchains/special events/triggers that check what your mystical class is that kill any attempt as you would have to touch the code of half of each campaign to add your option in. There is a reason why owlcat themself are not providing the vampire option so many would prefer to that stupid lich...

Yeah exactly this.

>> 4. The ability to force Wendu and Lan to join the party in Act I. You're the freaking main character. If you want both of these irreconcilable personalities to join your party and work together, the mangaka will find a way to make it happen.
> 4. That should be feasible. It is similiar to several triggers that John already programmed. I like the idea, give them a "Shut up, both your points are invalid because they will just lead to destroying your kind in a different way. You need to meet in the middle to survive." @JohN100x1 What do you think?

I will look into this. There's a whole series of etudes I need to investigate and patch in order to prevent any progression breaking bugs involving their side quests.

>> 5. Special Power to be able to use any equipment regardless of alignment/class/etc.
> 5. I'm not sure if you can set a flag to ignore such flags on everything.

There's no flag to ignore prerequisites when an equipment uses a prerequisite component. Implementing this would require replacing the game's components with a custom component that allows ignoring prerequisites. e.g. `PrerequisiteAlignment`, `PrerequisiteClassLevel`, `PrerequisiteStatValue`, ... etc. Quite a lot of boring patching.

>> 6. Additional class specific interactions. I'll have to think on this one. Maybe getting Hulrun and Ramien to play nice. Extra taunts to Minago/Nulkineth/etc.
> 6. John has already added several places where you get special dialogue. If you want more of them please make specific suggestions, where, what text, what result... Not making a promise they will all be implemented but that will at least tell us what places to think about.

I've only added 3 additional dialogue answers so far. It's easier in dialogues where no etudes are triggered because it can affect future events.

>> 7. I'm sure this one will be a bit controversial, but a more balanced version of the class. Or perhaps I should say less overpowered. Grim Dark Isekai Protagonist or something to make it clear there are some stakes and he might actually have to struggle a bit. This would be a lot of work too, but it'd mostly be tuning down most of the abilities and locking some of the more extreme overpowered abilities at higher levels.
> 7. If you want to see additional archetypes, even a less overpowered one for a harder run through be specific with your suggestion: name, description, general outline of what feature is gained at what level...

Someone actually suggested making a balanced version of the class when I first released my mod. I told them I would make a really underpowered class called `Side Character` with an almost empty progression sheet as a joke. I'm not the best with game balancing; I always end up making up something completely useless or completely overpowered.

Adding a new class that's balanced would require a lot of development time. Players' feedback usually tend to want things to be buffed so deciding where to limit the power level of the class will be difficult to determine.

**Comment by Mythalar** [comment]
[Alternate humain traits](https://github.com/microsoftenator2022/AlternateHumanTraits) already added the heritage screen for humans si I guess you could start here.

**Comment by kjk001** [comment]
> I think one option is enough. The only problem with implementation is maybe making the heritage selection appear since humans don't have a heritage selection by default.

Which is why I said we need more than one option to make that effort worth our time...

But yes if there is already another mod doing it that we can use as a base that would siqunificantly simplify it.

So Mythalars post opens two paths for us, use this mod as inspiration for the how to when not installed or make it an optional feature that is only available with that mod installed. Second option would be easier.

> Adding a new class that's balanced would require a lot of development time. Players' feedback usually tend to want things to be more powerful so deciding where to limit the power level of the class will be difficult to determine.
Which is why I told him to be specific with his initial wishes, that should greatly cut down on the initial guesswork on our part.

> I've only added 3 additional dialogue answers so far. It's easier in dialogues where no etudes are triggered because it can affect future events.
And I did say no promises even if he makes some suggestions. If we know the places where people feel IP should have extra dialogue we know where to check for consquences don't we?

**Comment by kjk001** [comment]
> This used to be the case but not anymore... because some users wanted OP abilities and special powers in the Mythic ability selection I made it accessible to non IP classes. The solution here should be to add a settings option in UMM to decide whether to exclude non IP classes from selecting these.

I had forgotten about that.

**Comment by Nerin3** [comment]
About point 3.
You could make a mythic that's treated as a Legend(for quests and everything), but with Isekai Protagonist flavor.(don't lose your mythic powers and still get to choose more feats, this could allow you to even add a prestige class that requires Isekai Protagonist on level 20)

**Comment by kjk001** [comment]
easier said than done Nerin, with they way the checks are set up we can't set the class to count just like a legend, we would either have to add an artificial legend level or go through the entire code with an if requirement == legend then change requirement (legend || custom) logic check.
Though that has just gotten me to wonder, the class definitions of the mythic classes are just normal classes, so could we define archetypes?
An Archetype would still be treated as the base class for the purpose of any and all dialogue but I think the mythic level dialogue doesn't support archetypes...

**Comment by JohN100x1** [comment]
My take on these suggestions
1. Will implement ✔️
2. Will implement ✔️
3. Will not implement ❌
4. Will think about it ⚠️
5. Will not implement ❌
6. Will implement ✔️
7. Will not implement ❌
