### ISSUE TITLE
2 Change suggestions for future release

### ISSUE THREAD

**Issue by kjk001** [JohN100x1/WOTR_IsekaiMod#107]
I have two thoughts that I thought I should at least put up to debate.

We should probably consider the deprecation and replacement of some features.
For example Kinetic Blast can now be gained through 4 different legacies while keeping compatibility to enhancements other mods made to it. So the special power has become somewhat redundant. A fourth or fifth Element selection for anyone that has a kinetic legacy would probably be a good replacement...

We might also want to consider adding some prerequisites for a few features. 
For example all the auto metamagic features could require the player to have the base metamagic feature as an easy restriction.

**Comment by JohN100x1** [comment]
For the 5.0.0 release kinetic power should definitely be removed since it is redundant now that legacies exist.
I think for the prerequisites we need to be careful not to make users feel like they are taking redundant feats re auto metamagic.
Maybe a UMM settings option to let users decide?

Aside from this, I also think the subclasses should be reworked somewhat in the 5.0.0 release. I'll create a new issue for this.

**Comment by JohN100x1** [comment]
@kjk001 I am going to remove the following blueprints and features for 5.0.0.

The reason I want to remove them is because I think they are redundant, especially with the paladin legacy.
- The extra benefit of smiting non-evil enemies is not alot because most of the enemies we fight in WOTR are evil.
- Smiting neutral or good characters does not fit with the idea of a Hero who fights against evil.
```
"TrueSmiteResource": "1d1029a9-d9ec-4fa2-8dd9-5e6bf449b019",
"TrueSmiteBuff": "bbb4182a-17a4-443c-88ba-28df72b218d2",
"TrueSmiteAbility": "516866eb-537d-4e16-9be6-585f7b237a10",
"TrueSmiteFeature": "5203aa1b-4553-4f24-aa9d-a1b238aa7495",
"TrueSmiteAdditionalUse": "96b4916b-dfdf-4cba-b1c0-96deeb9a0b6d",
"TrueMarkBuff": "89e23f11-d32b-46ef-9836-d136ea224e53",
"TrueMarkAbility": "ba3e0f3b-55fd-4443-952a-f44d2586d2a9",
"TrueMarkFeature": "8956e383-fe4b-4b41-83f4-d426b40d487c",
```

**Comment by kjk001** [comment]
at the moment the paladin version of the legacy gets both, so you also need to remove them from that progression.

I have removed the redundant legacy versions of hero and tactician because 5.0 is going to break our downward compatibility anyway with the way the archetypes are reworked
