### ISSUE TITLE
Subclass reworks for 5.0.0 (discussion)

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#108]
Discuss improvements, reworks, changes for the Isekai Protagonist and its subclasses here.
I have edited this description as the discussion evolved, so note that comments may not follow.

Changes/new features marked with ❗
Latest thoughts:
1. `Isekai Protagonist`: **Jack of all trades**
    - ❗ Gets a new line of feats/abilities that is a mix of feats/abilities from other archetypes
2. `Edge Lord`: **Melee focused**
    - Uses DEX for attacks
    - Has extra attacks
3. `God Emporer`: **Buffing focused**
    - ❗ Change casting stat to WISDOM
    - Has auras which buff allies (offense and defense)
    - Has stats/resistances that increase (gets immunities at higher levels)
    - ❗ Change auras to be a mix from `Hero` and `Overlord`
5. ❗ `Mastermind`: **Spellcasting focused**
    - ❗ Has arcanist feats i.e. Eldritch font
    - ❗ Gets a line of OP abilities restricted to the auto metamagics
6. `Hero`: ❗**Protection focused**
    - Good-aligned
    - Uses Charisma for attacks
    - ❗ Gets buffs to attacks when not duel wielding
    - ❗ Gets auras which protect allies
7. ❗ `Overlord` (replaces `Villain`): **OP ability focused**
    - ❗ Change casting stat to STRENGTH
    - Evil-aligned
    - Has many OP abilities (like the current villain)
    - ❗ Gets auras which empower allies' offensive

**Comment by JohN100x1** [comment]
@kjk001 @Nerin3 @Mythalar Ideas are welcome

**Comment by Mythalar** [comment]
> 1. Isekai Protagonist
>    
>    * An extra feature group that would give a whole bunch of OP abilities and Special powers

I don't really understand this one, a new kind of progression?

> 2. Edge Lord should get some feats that scale from DEX.
>
>    * Add a new feature called `Edgy Aura` which a similar effect to `Friendly Aura` and `Dark Aura`

IRC those auras do no scale with a stat, but perhaps a toned down/scaling WotR aura ? +1 attack/per round at level 8 and 15 for the whole party, and a party wide speed enhancement?
 
> 3. God Emperor should get a few more OP abilities (all non-villain classes too probably).
>    
>    * Another OP ability at 5th and 15th level.

I advocate for this for some time so I wont disagree here ^^ 
In my current run I play a God Emperor with three OP abilities at level 1 but no pet and 2 more QoLso  auto quicken, auto reach and auto selective.

[Here](https://github.com/JohN100x1/WOTR_IsekaiMod/issues/99#issuecomment-1475427623) I also made a suggestion for a (unique? at least matching) legacy that would add domain powers. But some OP abilities would do just fine.

> 4. Hero needs to be buffed to make it stand out more. e.g. more powerful features.
>    
>    * Another OP ability at 3rd and 17th level.

That would make it in line with Edge Lord I think.

> 5. Villain's study target feature should be replaced with another feature that affects spells. ([Villain - Studied target #100](https://github.com/JohN100x1/WOTR_IsekaiMod/issues/100))
>    
>    * I'm wondering maybe renaming the Villain subclass to Demon Lord ❓ and making the subclass a more generic evil class rather than a spell focused one ❓ This class does have alot of extra OP abilities so it would make sense that it would be powerful like a demon lord.

On this one I very much disagree since Demon is a mythic path by itself and it would be incoherent with other path (Villain could be Devil/Lich/Demon/Trickester and even Aeon).
Futhermore it's the only subclass that is more clearly spell focused (with OP metamagic), a more generic one would be redundant with IP and even Edge/Hero.
And it so very Momonga-sama !

Still for hexes since they can be used for a variety of things and witch hexes/conduit surge would be unique to this subclass and in line with the villain theme (killing hexes, nightmares etc...)
Gameplay-wise Villain has a little reduced spells choice since they have to be memorized ((which is nice for a cleaner spellbook by the way), but hexes can bypass this "issue" (chich is clearly not a real one :p )

**Comment by JohN100x1** [comment]
> I don't really understand this one, a new kind of progression?
An extra line of feat/abilities in the progression sheet. I think the base class needs some powering up.

> On this one I very much disagree since Demon is a mythic path by itself and it would be incoherent with other path (Villain could be Devil/Lich/Demon/Trickester and even Aeon).
Futhermore it's the only subclass that is more clearly spell focused (with OP metamagic), a more generic one would be redundant with IP and even Edge/Hero.
And it so very Momonga-sama !

Fair enough. I put :question: because I wasn't sure about this.

> Still for hexes since they can be used for a variety of things and witch hexes/conduit surge would be unique to this subclass and in line with the villain theme (killing hexes, nightmares etc...)
Gameplay-wise Villain has a little reduced spells choice since they have to be memorized ((which is nice for a cleaner spellbook by the way), but hexes can bypass this "issue" (chich is clearly not a real one :p )

I suppose so. I was thinking before that a new custom feature would allow for more flexibility but I can see now how hexes could work.

**Comment by kjk001** [comment]
I believe several users suggested that the Emperor should also get access to its own sub list of legacies. Mythalar referenced one of his own suggestions earlier in this thread.
I didn't do that at that point because it didn't have access to the original features that were replaced by the legacy and given how few OP Abilities he gets taking away the level 1 OP feat for that choice felt wrong.
But if more are added at higher levels perhaps that would be an option? Or since all classes are getting a slight buff perhaps just add it without replacing anything?

Regarding Hexes, the shaman legacy already adds them, so they are at the moment not villain exclusive. If Hexes are to be the villains thing restricting the legacy or adding some additional hex options available only to villain would grant him an edge there.

Overall it might make sense to go over the list of legacies now added and reconsider what subclass gets access to which. 
Right now the IP gets the full list. 
Making something like Kinetic Knight, Shaman, or Judge (once added) completely exclusive to specific archetypes might also help with making each Archetype more special?

**Comment by Mythalar** [comment]
> I believe several users suggested that the Emperor should also get access to its own sub list of legacies. Mythalar referenced one of his own suggestions earlier in this thread. I didn't do that at that point because it didn't have access to the original features that were replaced by the legacy and given how few OP Abilities he gets taking away the level 1 OP feat for that choice felt wrong. But if more are added at higher levels perhaps that would be an option? Or since all classes are getting a slight buff perhaps just add it without replacing anything?

Emperor could get a legacy at level 1 and just one more instead of two later on (probably earlier than now so perhaps 6/12/18 instead of 10/20)

> Regarding Hexes, the shaman legacy already adds them, so they are at the moment not villain exclusive. If Hexes are to be the villains thing restricting the legacy or adding some additional hex options available only to villain would grant him an edge there.

I can be mistaken but when I looked into new legacies the shaman only added shaman Hexes, that are fewer in number and restricted by the chosen spirits.

It would still make sense to make the witch hexes progression exclusive to the Villain since some specific Hexes are quite useful/flavorful.

> Overall it might make sense to go over the list of legacies now added and reconsider what subclass gets access to which. Right now the IP gets the full list. Making something like Kinetic Knight, Shaman, or Judge (once added) completely exclusive to specific archetypes might also help with making each Archetype more special?

I think completely exclusive legacies would be a pity since it would only remove build possibilities.
Form me those are two sides of the same coin:
- a list restricted to what is flavorful and coherent with mechanics (Emperor would be more divine, Villain more arcane/evil etc...)
- open the subclass to the entire list and be done with it. After all you can select what you want as a dual legacy (or could earlier?) and subclasses could be defined in some other ways (Hero could have two legacies at level 1 or something since it it to be buffed)

**Comment by kjk001** [comment]
I was unaware that there is a big difference between those hexes since I don't really use either.
Ok so a witch based alternative still makes sense.

At the moment dual class legacy permits selecting everything because in the first batch the only legacies that really should be completely locked as a second option were Paladin and Dread Lord and those were automatically alignment locked.
Now we have a lot more options and as I  said might consider further restrictions that would then apply in the dual legacy option as well.

I liked the Villain as a spellfocused evil character, for melee focused evil characters I tend to just use Edge Lord. Rather than change the Villain to melee perhaps split the evil subtypes into two, Mastermind(the classical spellfocused villain) and Cultivation Novel Protagonist(because I can think of no other group that encapsules Chaotic Evil as well as them while mostly being melee focused)...

**Comment by kjk001** [comment]
`bp.AddComponent<PrerequisiteNoArchetype>(c => { c.m_Archetype = EdgeLord.GetReference(); });` so what I am considering is adding a bunch of conditions like that directly to the relevant progressions, so that even if the option appears in the dual legacy list the relevant archetypes can't pick them.
As I said for Paladin and Dread Lord that did not appear necessary at the time but now we have a lot more options that should be locked for specific Archetypes.

**Comment by Mythalar** [comment]
> I was unaware that there is a big difference between those hexes since I don't really use either. Ok so a witch based alternative still makes sense.

Some are quitedefining even so that's cool, and I also insist on the possibility of Conduit Surge since it would give an "active" ability that is not replicated elsewhere. Thematically the evil wizard that exert himself for his grand spell is nice I think.

> At the moment dual class legacy permits selecting everything because in the first batch the only legacies that really should be completely locked as a second option were Paladin and Dread Lord and those were automatically alignment locked. Now we have a lot more options and as I said might consider further restrictions that would then apply in the dual legacy option as well.

Fair but tricky for some (bard or skald for example, since they are really not good or evil and can be useful in any kind of build). Totally agree on those with a clear alignment restriction though.

> I liked the Villain as a spellfocused evil character, for melee focused evil characters I tend to just use Edge Lord. Rather than change the Villain to melee perhaps split the evil subtypes into two, Mastermind(the classical spellfocused villain) and Cultivation Novel Protagonist (because I can think of no other group that encapsules Chaotic Evil as well as them while mostly being melee focused)...

Also agree, the current Villain could be a Mastermind, INT caster focus (also neutral perhaps?) and is nice as it is now but switch studied target for hexes. 
I would replace the Dark Aura with a scaling aura that would allow the caster to bypass enemy spell immunities (Mind-affecting, Death, Paralysis and so on but not elemental immunities), with perhaps just the -2 saves at lvl 10. Ideally you could choose what effect at any given level (5,10,15 and no spell immunity at 20?)

The Cultivation could have feature from specific melee archetypes around there (some abilities from the Two Handed warrior are unique IIRC) and focus on STR. The Dark Aura could stay as it is (a generic penalty is nice for build like dreadknight etc...)

Corrupt aura would still be given to both of them since evil parties are often bolstered with dark powers...

**Comment by kjk001** [comment]
> Fair but tricky for some (bard or skald for example, since they are really not good or evil and can be useful in any kind of build). Totally agree on those with a clear alignment restriction though.

See above, there are other locking options that are not alignment based, I just didn't apply them at the time because they were already covered by the existing alignment lock for those options.

Please note that the chaotic evil melee version does not have to be called Cultivation Novel protagonist. When thinking evil melee mc that was simply the first group that came to my mind as I have yet to find one of those that was not a horrible person in at least one aspect.

**Comment by Mythalar** [comment]
> Please note that the chaotic evil melee version does not have to be called Cultivation Novel protagonist. When thinking evil melee mc that was simply the first group that came to my mind as I have yet to find one of those that was not a horrible person in at least one aspect.

Noted, Abyssal Lord could be ok but same issue as before since there already is a demon mythic path.

Regarding Mastermind/caster I'd rather have some unique effects like bypass spell immunities (if doable for sure) since I think damage bonuses are quite covered in diverse ways (direct + damage, auto bolster, sneaky magic, magic amplification etc...).

As a very much caster oriented player I find the current Villain as a castery subclass nearly perfect except for studied target (hexes?) and the impossibility to use a lot of CC spells on somes foes, which is sad because they are litteral "traps" from a mastermind.

**Comment by Mythalar** [comment]
Then I would shamelessly pile up on @Nerin3 suggestion : 
- Less OP abilities than current Villain,
- a mandatory Abyssal bloodrager legacy
- the passive effects of the [sorcerer Abyssal bloodline](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Abyssal+Bloodline)
- [Greater Power Attack ](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Greater+Power+Attack) somewhere
- a dual legacy to choose at lvl 1?

**Comment by Mythalar** [comment]
In the end, regarding subclasses as a whole, I would suggest giving them at lvl1 an imposed legacy and one to choose, but they could not choose the dual legacy feat afterward (except God Emperor?)
This would also limit the issue of the retroactive benefits issues (if still there?) and give them some iconic skills.

- Hero : Paladin + 1 goody/generic
- God Emperor : Domain Lord (+ dual OP?)
- Mastermind : Witch + 1 caster/baddy
- Abyssal Lord : Abyssal Bloodrager + 1 baddy/generic
- Edge Lord : Thief + 1 (?)
- IP : any two 

It could be seen as a step back but subclasses as of now already have quite unique abilities (main stat etc...) and just lack some narrower "direction".
This way there would be some place for custom, more RP coherence and easir to "balance" if quite everyone has some dual legacies (just a matter of adjusting the number of bonus feats/OP/SP)

**Comment by Nerin3** [comment]
I would keep mastermind as Arcanist type of caster though.

**Comment by kjk001** [comment]
While I think the available legacies should thematically be locked I do not like the idea of forcing the choice of the first one with a single option.

As a mastermind I would prefer tactician to witch for my first choice because thematically it fits just as well and it fits my evil planner better. 
As an Edge Lord going Kinetic(neutral), Paladin(Good), or Dread Lord(Evil) also tends to feel more natural for my first choice than rogue.

So while a lot more choices need to be more narrowed down on who gets access to them I think hardcoding the first choice will actually push a lot of people into boxes they wouldn't want and were pretty glad to get out of with the broader legacy options introduced in 4.0.

**Comment by Nerin3** [comment]
I wouldn't lock any legacy behind a archetype, if anything only behind an alignment. But that is my opinion though.

**Comment by kjk001** [comment]
Those are still legacies, just a much smaller list for now ;)

**Comment by Nerin3** [comment]
Also I think some legacies are much weaker than other, take Kineticist legacy: It's a full class on its own, while Tactician is 1/3 of Inquisitor.

**Comment by Nerin3** [comment]
Personally I think Kineticist powers should be a separate op ability instead of legacy that you can chose on lvl 1.

**Comment by kjk001** [comment]
It is a bit more than that with the addition of tactics enhancing feats from other classes, was one of the first 3 made and I still like it even if we have now buffed all other legacies a bit beyond what it grants.

If you have a good idea for buffing it I will consider it.

Actually most of the options are now balancing wise at the level of Kineticist. With some like the Seeker of Truth and Chimera it is just less obvious because you don't really see that in reality they are even more than a full class progression till you reach their end.

Only the tactician really lags behind and I still like him anyway...

**Comment by Mythalar** [comment]
Regarding Mastermind, and to complete my previous post : Studied target could be specificly replaced with [Eldricht Font](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Eldritch+Font) progression since it's quite thematic for an evil caster. And if Arcane Discoveries could be added to the list... :p

**Comment by kjk001** [comment]
and in all the recent posts starting a debate about legacies here we might now have successfully burried the one suggestion and debate that would actually be higly relevant to John.

@JohN100x1 
Quick recap:
everyone aggrees that the villain as a scheming type villain is perfect and only Studied target should be chaanged on it.
However it could be renamed to Mastermind with a second more melee focused archetype being added. 

If you ignore the last 12 posts you can read up the ideas that came together on that idea before that.

**Comment by Mythalar** [comment]
Yes so more on point : 
- Mastermind blabla Eldricht font progession etc...
- Abyssal Lord : a real question here. Would it be doable to make a kind of Rageshaper Shifter that would work with weapons?
As it is it could be quite thematic with a very angry big bad boy?

**Comment by JohN100x1** [comment]
> Quick recap:
everyone aggrees that the villain as a scheming type villain is perfect and only Studied target should be chaanged on it.
However it could be renamed to Mastermind with a second more melee focused archetype being added.
>
> If you ignore the last 12 posts you can read up the ideas that came together on that idea before that.

Thanks for the summary @kjk001, it looks like you guys are really passionate about legacies.

So this is what I've gathered so far.
1. `Villain` is renamed to `Mastermind` (great name btw) and the study target feature is replaced with arcanist feats i.e. Eldritch font.
     - My question would be, Is the evil alignment removed from this archetype so that it's a generic caster?
2. A new evil melee archetype is added `Abyssal Lord` :question: I don't really like the name to be honest. The word "Abyssal" makes it sound like the player comes from the abyss. I think it's best keep the villain naming.

Here's a high level summary of how I envision the archetypes for 5.0.0:
New ideas marked with ❗  and ideas that need refinement marked with ❓.

1. `Isekai Protagonist`: **Jack of all trades**
    - ❗ Gets a new line of feats/abilities that is a mix of feats/abilities from other archetypes
2. `Edge Lord`: **Melee focused**
    - Uses DEX for attacks
    - Has extra attacks
3. `God Emporer`: **Buffing focused**
    - Has auras which buff allies
    - Has stats/resistances that increase (gets immunities at higher levels)
4. ❗ `Mastermind`: **Spellcasting focused**
    - ❗ Has arcanist feats i.e. Eldritch font
    - ❗ Gets a line of OP abilities restricted to the auto metamagics
5. `Hero`: **❓❓❓ focused** idk what the identity of Hero should be
    - Good-aligned
    - Uses Charisma for attacks
    - ❓ used to have the true smite ability which is now part of a legacy
6. `Villain` or `Abyssal Lord`:question:: **OP ability focused**
    - Evil-aligned
    - Has many OP abilities (like the current villain)

That's how I envision the archetypes so far. The most problematic is the `Hero` because I don't know what it should focus on.
I could give it auras which buff allies but that would be too similar to `God Emperor`. The `Hero` needs a new set of feats/abilities that will make it stand out and have a more solid identity. This is probably the issue I'm struggling to think about the most at this moment.

**Comment by Mythalar** [comment]
Very much agree with this.
The Mastermind could be of suite any alignment I guess.

That's without balancing questions?

Regarding Hero I don't really have ideas that are not already in other subclasses or paladin legacy...
Something like getting buffed when hurt/controlled etc... for tenacity? Or a burst of divine damage ?
Something like the Argonaut of Bell Cranel

**Comment by kjk001** [comment]
To me a hero is a fighter that is more focused on protecting his allies and the innocents. So a bit like the Base class a Jack of all Trades as long as those Trades are heroic.
Less total Buff auras (and no true full immunities gained from ascending to godhood) then the God Emperor but in exchange more OP and Special Power Options to develop personal freedom. If we can do it mechanically perhaps add some abilities to switch places with allies when they are attacked to protect them?

Edge Lord to me is more of a solo focused melee build rather than a team player. Since the buffing of the heroic legacy will actually add lay on hands and other team based paladin skills I would take that away from the Edge Lord, then hero would besides IP be the only archetype with access to it. 

So thematically we have differences there and even if we at some point create two archetypes that are mechanically identical, they can still differ in their rp flavor, the anti paladin to the paladin...

**Comment by Mythalar** [comment]
Then what about a self damaging aura (like the Martyr) that would give a X damage reduction to the whole party (scaling with level).
I think ive seen the switch place thing somewhere in a mod but can't recall right now.

**Comment by Mythalar** [comment]
Ultimate protector (toggle ability) : confers "level" damage resistance, "level/4" bonus to AC and saving throws to the whole party.
Hero takes "level" (?) unstoppable damage each round and can only be healed by himself.

Something like that (or perhaps the other way : cannot heal himself?).

**Comment by CGNefarious** [comment]
If Edge Lord is for dex builds focused on getting lots of attacks in a round, how about making Hero about two-handed weapons or sword and board, and instead focusing on getting a lot of damage on fewer attacks. Maybe something like applying 2x Cha to weapon damage rolls when not dual wielding, or a vital strike like ability that works on every attack in a full attack?

I also like the idea of a protection focus. Heroes in Isekai are always about protecting their friends, so it makes sense.

**Comment by Nerin3** [comment]
Maybe instead of Villan/ Abyssal Lord name him Overlord

**Comment by Necht** [comment]
I think that for the Hero it is also necessary to change his ability channels positive energy.

1d6 for each level. And at level 20, let him always heal the maximum amount of health. Just like a paladin.

**Comment by Mythalar** [comment]
> I will open another issue in the future for discussing the specific features when I begin implementation.

Ok, I'll have to remember my ideas :p 
Speaking of auras, I think that would be more intuitive that they all be fused in a subclass-unique level scaling ability. Easier to follow trough leveling than splitting them in multiple features.
Mastermind could be the one to have an debuffing aura (like the siphoning aura)

**Comment by kjk001** [comment]
Not sure if this is a good idea, but we could change the God Emperor to actually use wisdom for casting and the new Overlord to use strength.

**Comment by Mythalar** [comment]
> Not sure if this is a good idea, but we could change the God Emperor to actually use wisdom for casting and the new Overlord to use strength.

Proposed this some time ago and it was rejected.

To be honest it does not change so many things but it could be useful to some legacies that are Wisdom based (a psychokineticist could translate the trials and errors with new powers).

Totally agree with you for Overlord.
Still have a draft for auras that would specific to each subclass to enforce their theme (as of now I've protection for Hero, overall buff for God Emperor, Damage buff for Overlord, debuff for Overmind, still in work for Edgelord though)

**Comment by kjk001** [comment]
if it was already rejected, then it was rejected.
I was unaware of the previous request.

**Comment by JohN100x1** [comment]
@Mythalar I actually forgotten about the wisdom casting stat suggestion when I implemented the changes. Now that we are reworking subclasses again I think we can discuss and implement this.

I agree that God Emporer should use wisdom as the casting stat. I think some features need to be changed/implemented to accommodate this:
1. Creature backgrounds that replace certains skills (e.g. persuasion) to use wisdom. These new backgrounds can be discussed here https://github.com/JohN100x1/WOTR_IsekaiMod/issues/114
2. Features from the Isekai Protagonist progression (for example `Quick-footed`) that scale with charisma should be repalced with wisdom scaling.

For the Overlord suggestion, I find it funny that strength can be used for spell casting but I'm fine with implementing this if you guys think it fits the subclass.

Some personal thoughts:
Just like in kingmaker, the player becomes the ruler of a city. So, my original thinking was that a ruler needs to have good persuasian (i.e. good charisma) to rule people, which was why I selected charisma as the casting stat for the `Isekai Protagonist` class. It seemed to be the most sensible stat use for rulers. Discussing the casting stat changes has now opened my mind to new possibilities. It makes sense for an evil Overlord to rule through strength rather than persuasion, and the God Emperor to rule through wisdom like a philosopher king. I very much appreciate these discussions we are having!

**Comment by Mythalar** [comment]
Actually there are already quite a lot of background that use Wis for persuasion (acolyte) or even for knowledge skills (don't remember the name right now).
But could be useful to make a "package".

Agree with you on the God Emperor/personal features.
I guess there will be a separate thread for progression or feature discussions.

As for the Overlord: there is actually a feat that add Str to intimidation rolls so that's not so stretched!
Regarding casting stat Homebrew archetypes added a witch subclass that has spells/hexes scaling based on constitution and that's quite fun (actual unchained version of a real archetype).

Same way Edgelord could focus on Dex so to each their own :p

Setting a corresponding main stat can have a nice side effect regarding legacies since some would be "natural extensions" of the subclass, and selecting another one can be done at the expense of more stat spreading.
This way it would not be necessary to, IE, add uses/day to domain powers based on another stat than wisdom.
(Someone else can choose the legacy but at some cost)

**Comment by kjk001** [comment]
I was just about to post that a high enough strength has a charisma all of its own when it comes to diplomacy...
Almost as if people just don't want to say no to you...

**Comment by Nerin3** [comment]
I wouldn't change casting stat to strength for Overlord though, I'll stick to Charisma or Intelligence (Depends if you prefer Charismatic Overlord or a Cunning one).
Str casting would warrant another archetype akin to: Muscle Wizard.

**Comment by Necht** [comment]
What do you think about adding this toggle ability to the Hero or making it a full-fledged separate legacy along with other auras that I [suggested](https://github.com/JohN100x1/WOTR_IsekaiMod/issues/111#issuecomment-1480000169)?

[HEROIC AURA](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Heroic+Aura)

But to exchange [HEROISM](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Heroism) for [HEROISM, GREATER](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Heroism,+Greater).

You can also add these auras as a separate ability:
1. [UNBREAKABLE HEART](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Unbreakable+Heart)
2. [BULL'S STRENGTH](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Bull's+Strength) and others are the same.

I think it would be great for a hero or a separate legacy for a hero. You can also add other auras, but not too much and not too strong. 
It must be remembered that the power of the Hero's friends comes from the heart, not from muscles or spells.

**Comment by JohN100x1** [comment]
> I wouldn't change casting stat to strength for Overlord though (feels weird), I'll stick to Charisma or Intelligence (Depends if you prefer Charismatic Overlord or a Cunning one).
IMO Str casting would warrant another archetype like a Muscle Wizard or something (as if made for this specific purpose).

I guess the casting stat would depend on whether we want the Overlord to be desinated a general evil archetype or an evil _melee-focused_ archetype. I'm fine with either really, the Mastermind could serve as an alternative for a cunning "overlord" if we have a consensus (or majority agreement) of the Overlord casting stat. Also I don't really want to implement any more archetypes than the ones we discussed before for 5.0.0.

> What do you think about adding this toggle ability to the Hero or making it a full-fledged separate legacy along with other auras that I https://github.com/JohN100x1/WOTR_IsekaiMod/issues/111#issuecomment-1480000169?
> ...

Can you give me detail about this ability? A list or description of all its effects would be good.

**Comment by Necht** [comment]
> Can you give me detail about this ability? A list or description of all its effects would be good.

What do you mean? 
[HEROIC AURA](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Heroic+Aura) - this is Aivu's passive ability. She is our companion on the path of Azata.

**Comment by Mythalar** [comment]
Would personaly emphasize the melee part for Overlord.

Thoughts of mine : all subclasses could/should have a level scaling aura that enforces their theme.
Based on what would be thematical (Isekai level = IL)

**God Emperor** (global buff) 

- Aura of Majesty : sacred bonus of 1/2 IL to the party attributes + 1/4 IL to AC + 1/4 IL to saving throws

No more siphoning aura/dark aura/aura of divine fury (damage is covered by increased stats).

- Celestial realm much sooner (lvl12?), perhaps make it so it also extends spells for the whole party (or another "minor" but useful metamagic)

At lvl 20 it would be nerfed compared to the current iteration but if God Emperor gets a legacy and 1 or 2 more OP abilities it would be nice.
As of now bonuses are quite repititive along the road but at the end the bonus/penalties are really strong without doing anything...

**Mastermind** (debuff)

- Siphoning aura : -1/3 IL to attributes of every creature in a 40 feets radius.

I find this one a little on the weak side but -1/2 IL would be too much. Something in between perhaps like -(2 + 1/3 IL) for a max of -8 perhaps ? (same as cumullative Dark aura and siphoning auras of the current God Emperor)

With an arcanist exploit progression (eldricht) it would be a nice all around caster.

**Overlord** (+damage)

- Dark aura : +1/2 IL to attack damage and hit point damages from spells + 1/4 attack bonus to the party 40f radius. Attacks are considered evil.

**Hero** (protection)

- Aura of golden protection : +1/2 DR + 1/3 sacred bonus to AC + 1/3 sacred bonus to saving throws to the party 40f radius (+ a little regeneration perhaps?)

**Edge Lord**

Tricky since more of a loner...
Would have thought of a +X attack/round bonus to the party + enhancement to speed?


I think something like that would shrink the growing number of Isekai abilities and simplify them.
They should also be granted soon (5 or something) to limit the power spikes and make it so every level is a gain.

The numbers are a little weird but I think a straight +10 (1/2 IL) bonus to AC/saving throw is a tad much. It's less of an issue for damages since numbers already can go wild.

**Comment by Nerin3** [comment]
@JohN100x1 I'm mostly against STR as casting stat, because it's against the concept how casting should work for people, it's the reason why other classes still use mental stat for spellcasting even if they're martial focused class, as casting through physical stat without a proper explanation doesn't really make sense in the world of pathfinder.

**Comment by Mythalar** [comment]
I've mixed feelings about this.

I think justification can be found easily enough there there already exist some archetypes with spellcasting based on physical stats (granted, mostly constitution).
But that's also true that a character based entirely on strength would be quite more powerful than a charisma/int/wis based one since strength would give +hit, +dmg, +spell DC etc...

A strength focus character would also probably rely more on buffs which are not affected by casting stat except for bonus spells...

I think it was a good idea to discuss this, but it's not really worth to actually implement.

Still a good idea to make a wisdom based god emperor since it allows some choices for party composition/gear but further rework could be more focused on abilities than casting stat.

**Comment by JohN100x1** [comment]
I will revert the STR casting stat change.

**Comment by ThePiggyGalaxy** [comment]
I was wondering, if instead of / as an alternative to hero / villain there should just be one subclass regarding alignment types with all their features being applied in the way that would fit the character's alignment, so instead of smite evil for a lawful neutral character, it would be smite chaotic. And for characters with a mixed alignment they would need to pick between which opposing alignment they would smite.

If this is an additional class you could realign the hero and or villain class more to their characteristics (like how villain's spell casting focus was changed into mastermind) instead of just being anti-good or anti-evil. 
Hero for example could get an enemy bane instead of a smite with 2 sets of favoured enemies. I actually like how overlord is being handled, though I don't really like it's alignment restriction, since an overlord is more like an overly domineering and powerful ruler and though (e.g.) Ains would be evil aligned, that's more because of his inability for compassion since he became an undead (and he's still quite benevolent to his actual allies and subject) of cource there are more evil people fitting the description of an Overlord, but I don't believe all of them are.

> **Overlord** (+damage)
> 
> * Dark aura : +1/2 IL to attack damage and hit point damages from spells + 1/4 attack bonus to the party 40f radius. Attacks are considered evil.

Following my earlier mentioned opinions this would instead be:

* Domineering aura : +1/2 IL to attack damage and hit point damages from spells + 1/4 attack bonus to the party 40f radius. Attacks are Aligned with (one of) your alignment(s).

And other such a minor changes for hero's sacred type bonus
