### ISSUE TITLE
Kinetic knight legacy : missing burn reduction

### ISSUE THREAD

**Issue by Mythalar** [JohN100x1/WOTR_IsekaiMod#115]
The legacy based on kinetic knight, that also adds energize weapon, does not seem to include the -1 burn reduction on kinetic blade (and energize weapon should be included?).

As it is I have 1 burn/hit on my Edge Lord :p 

Only tested with Negative element from [Kineticist Expanded Elements mod](https://github.com/SpencerMycek/KineticistExpandedElements) though.

**Comment by kjk001** [comment]
Could you try if the same works on an actual kinetic knight as a kineticist archetype?
Unless the burn reduction introduces yet another new concept bugs like that should already happen there.

**Comment by Mythalar** [comment]
Ok I'm quite lost there to be honest.

On my one week old Through the Ashes Edge Lord run I had a Kineticist Lord legacy with Kinetic blade and Energize weapon at lvl 1 but no cost reduction. I would add that there were not any addition of Darkcodex mod, notably the Whip infusion (automatically granted to kinetic knight).

This morning if I make a new IP (or Edge Lord, tested both) it has all the goodies from DarkCodex, the cost reduction, but not the Energize Weapon.

Really strange but good for me so I guess you could consider it solved (mojo magic)

**Comment by Mythalar** [comment]
Perhaps that's your new way of automaton legacy patch or something?

**Comment by Mythalar** [comment]
Also noticed that some previously implented legacies (Dreadlord etc...) also gained their full abilities, which is very nice. Guess that's the same thing.

**Comment by kjk001** [comment]
Not all previous ones, paladin is still missing because I was testing the new logic on warrior and edge lord and by the time I was done with that the patch was ready for rollout so paladin became prio number one for patch 4.3 instead.

The missing energize weapon is due to load order, the new patch method had a minor problem here that makes it a 50-50 chance for me on if it appears, chance may vary based on what mods you have... 
So it was there when I tested then gone the next start when I didn't check if it was there. 
I moved that check back by a step in the load order and it should be stable in 4.3.

I did consider just leaving it out for good though after noticing it because the build seems a bit too popular when compared with a lot of other options, so it might do with a bit of depowering...

**Comment by Mythalar** [comment]
>I did consider just leaving it out for good though after noticing it because the build seems a bit too popular when compared with a lot of other options, so it might do with a bit of depowering...

Agree with you on this point (so many kinetic blade attacks as a Edgelord, even without two weapons, is already really powerful)
