### ISSUE TITLE
Paladin Legacy bug

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#116]
User reported bug (version 4.1.1):
> The Lay On Hands ability from the Paladin Legacy does not work.
It appears to not count Isekai levels as Paladin levels - so it does 0d6 healing and is usable 0+CHA times per day.
It also requires Lawful Good alignment to use.
>
> Tangential issue: Is it possible to make the Extra Smite feat work for the True Smite ability?

I just tested this and the lay on hands ability does not heal at all. I think the 4.2.0 update fixed the number of usages but the healing isn't working. The ability itself also requires lawful good alignment.

**Comment by kjk001** [comment]
Tangential issue: only if we add the resource used by true smite as a reference to that feat but since in 4.3 the class and all its features should be properly fixed to use paladin feats instead so that would not be an issue in it.

The lawful good restriction might be a killer though and require me to instead of hacking into the base class to copy all ressources over the way you had done for smite.

I will test that and in the worst case recreate lay on Hands and Mercies entirely because it would be unfair to restrict it like that for the IP.

**Comment by kjk001** [comment]
```
[HarmonyPatch]
        private static class AbilityAlignment_IsRestrictionPassed_Patch {
            [HarmonyPatch(typeof(AbilityCasterAlignment), nameof(AbilityCasterAlignment.IsCasterRestrictionPassed))]
            [HarmonyPostfix]
            public static void PostfixCasterRestriction(ref bool __result) {
                if (settings.toggleIgnoreAbilityAlignmentRestriction) {
                    __result = true;
                }
            }

            [HarmonyPatch(typeof(AbilityTargetAlignment), nameof(AbilityTargetAlignment.IsTargetRestrictionPassed))]
            [HarmonyPostfix]
            public static void PostfixTargetRestriction(ref bool __result) {
                if (settings.toggleIgnoreAbilityAlignmentRestriction) {
                    __result = true;
                }
            }
        }
```
found their method, so instead of their if block we would need a condition that checks if the alignment is good, if the ability was a pala ability and if the user had the correct legacy.

Yeah, just hardcopying every feat might be easier might it not?

**Comment by kjk001** [comment]
@JohN100x1 so good news I was wrong on what the easiest solution would be and we have a working patch that will fix the alignment issue. Bad news is I am not sure it will work retroactivly and currently have no save to test it on.
So the user might have to reskill the character once patch 4.3 that fixes it rolls out.
