### ISSUE TITLE
[4.3.0] Bloodrager Legacy - No Bloodlines

### ISSUE THREAD

**Issue by NightOwlByDay** [JohN100x1/WOTR_IsekaiMod#129]
**Describe the bug**
When  trying to use the Bloodrager Legacy - Chimeric Rager, the list for selectable Bloodlines is empty.
If the Mod [TabletopTweaks-Base](https://github.com/Vek17/TabletopTweaks-Base) is used in conjunction with the [TabletopTweaks-Core](https://github.com/Vek17/TabletopTweaks-Core) Mod, the "Aberrant" and "Destined" bloodlines (added by the "Base" Mod) become available for selection.

**To Reproduce**
1. Create Isekai character and select "Bloodrager Legacy - Chimeric Rager" as Legacy
2. Continue character creation till Bloodline selection

**Expected behavior**
At bloodline selection, all bloodrager bloodlines should be available.

**Screenshots**
![image](https://user-images.githubusercontent.com/130167830/230645852-07701aa1-73ce-444d-9ca5-b58155301679.png)

**Comment by kjk001** [comment]
this is weird, for me the list is normal but I do believe you because I got a similiar report by someone claiming to have the same problem with the inquisitor domains, could you please:
1.  check  if that list has similiar problems for you?
2. Post me your player.log?

![image](https://user-images.githubusercontent.com/121681604/230650016-eb1b47df-d133-4983-b24a-0030f6a4012f.png)

**Comment by kjk001** [comment]
also, assuming you are affected by both problems, would you mind running a version of the mod with expanded debug messages for me to help me figure out what is causing it?

**Comment by NightOwlByDay** [comment]
Hi @kjk001, your hunch was correct, the list for domains is similarly empty when I try to create an isekai character with the Inquisitor Legacy - Domain Lord.

![image](https://user-images.githubusercontent.com/130167830/230653839-8c3c1084-622a-468b-9379-292fb7a878f2.png)

Player.log:
[Player.log](https://github.com/JohN100x1/WOTR_IsekaiMod/files/11180555/Player.log)


I'd be happy to help. How do I activate the expanded debug messages?

**Comment by kjk001** [comment]
You can't on your own, I would have to create a specific build where I add a lot of checks and messages around the relevant sections of the code to try to figure out what is wrong.

Which would be an unofficial build not published or scanned on nexus, hence the question...

**Comment by NightOwlByDay** [comment]
Understood
Still fine by me.

**Comment by kjk001** [comment]
ok, the monk patch is finished, I will reset my git to the 4.3 release and write in some additional checks to figure out thisproblem at some point tommorow then upload the file here

**Comment by kjk001** [comment]
[IsekaiModDLLForLogging.zip](https://github.com/JohN100x1/WOTR_IsekaiMod/files/11181166/IsekaiModDLLForLogging.zip)
so this is just a zip of the dll with some extended logging.

You will get a new line in the player.log:
[IsekaiMod] Patching Bloodrager bloodlines

Ideally your next few lines after that should be:
[IsekaiMod] Bloodrager Bloodline Selection initialized checking its various element lists
[IsekaiMod] Features Reference Array Length= 24
[IsekaiMod] Features Elements Array Length= 0
[IsekaiMod] Features normal Array Length= 3
[IsekaiMod] Features all Array Length= 24
but you might also get a warning that the selection isn't initialized yet instead or different numbers for the various arrays, depending on what the lines are we should be able to tell at least a bit of the problem.

I uploaded just the dll because the rest of the files should be used from the official release...

**Comment by NightOwlByDay** [comment]
That was quick, thanks for taking the time to analyse an issue that seems rather isolated to me and apparently one other person :).

Player.log with TabletopsTweaks_Base disabled:
[Player.log](https://github.com/JohN100x1/WOTR_IsekaiMod/files/11181997/Player.log)

`[IsekaiMod] Patching Bloodrager bloodlines
[IsekaiMod] Bloodrager Bloodline Selection initialized checking its various element lists
[IsekaiMod] Features Reference Array Length= 0
[IsekaiMod] Features Elements Array Length= 0
[IsekaiMod] Features normal Array Length= 0
[IsekaiMod] Features all Array Length= 21`

Player.log with TabletopsTweaks_Base enabled:
[Player.log](https://github.com/JohN100x1/WOTR_IsekaiMod/files/11181980/Player.log)

`[IsekaiMod] Patching Bloodrager bloodlines
[IsekaiMod] Bloodrager Bloodline Selection initialized checking its various element lists
[IsekaiMod] Features Reference Array Length= 2
[IsekaiMod] Features Elements Array Length= 0
[IsekaiMod] Features normal Array Length= 2
[IsekaiMod] Features all Array Length= 23`

**Comment by kjk001** [comment]
Well yes, it kept bugging me, adding some log messages doesn't take long, and my D&D game started a bit late...

Quick follow up question, do you play the enhanced edition or base edition?

I have an idea for the fix either way and will apply it for 5-0-0 but it would be nice to know if this is another somewhat dodgy place in the code in terms of stability of initialization or a place where the logic between editions simply differs...

**Comment by NightOwlByDay** [comment]
I play the with enhanced edition.

**Comment by kjk001** [comment]
Then I have no idea why the reference array would not be initialized.
Ah well, avoiding it from now on...
