### ISSUE TITLE
I noticed this thing after picking mastermind

### ISSUE THREAD

**Issue by Nerin3** [JohN100x1/WOTR_IsekaiMod#136]
I got Arcanist Spellbook with 0 levels in it.
![image](https://user-images.githubusercontent.com/1911661/232623456-ea6096db-ac9b-4c28-8f49-6f7ff8f1e2ab.png)

**Comment by JohN100x1** [comment]
The arcanist's consume spells feature I patched references both the arcanist's spellbook and the mastermind spellbook which causes this to happen. If you play the arcanist class it would also show mastermind 0.

Instead of patching the original arcanist feature, I'll need to create a duplicate consume spells feature that would reference the mastermind spellbook.
