### ISSUE TITLE
Isekai Background Suggestions

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#4]
Some ideas:
- A background that gives +1 bonus to all attributes ✔️

**Comment by Nerin3** [comment]
Some ideas with some flavour text as well:
Isekai otaku:
You've waited for this moment your entire life, now is your chance to live your dream. 
+2 to all skills except of diplomacy(persuasion)
Former Demon Lord:
You're actually a reincarnation of a powerful Demon lord that was defeated 1000 years ago. Now stuck in your new form you embark upon a journey to reclaim what's yours.
20 lightning DR and +2 to STR
Gamer:
Last thing that you remember before coming to this world was you playing Pathfinder: Wrath of The Righteous, just before a lightning struck your house.
Due to meta knowledge + 10 to all lore and knowledge checks, as well as Perception when it comes to finding traps.

**Comment by JohN100x1** [comment]
These sound amazing! I'll add them in the next update.

**Comment by jedi7000nathan** [comment]
Ultimate Computer Programmer: increase initiative by 10 and increase to damage for all weapon types. Also gives a bonus to perception and knowledge arcana and knowledge world. You are aware you are in a world that is a game and thus can exploit that knowledge to your advantage allowing you to outrun enemies, strike harder and see things that others can't. Basically Kirito exploit

**Comment by JohN100x1** [comment]
maybe "beta tester" would be a more appropriate name?

**Comment by Nerin3** [comment]
Dimensional Bag as background? IMO it should stay as an OP ability, but if anything, just change its name to 'Inventory', because in isekai most character get their unlimited storage space as inventory ability rather than an infinite bag of holding.
#38

**Comment by JohN100x1** [comment]
yeah i put a ❓ because i wasn't sure about it. I like the name change, makes it sound more game-like.
