### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Magdi76** [JohN100x1/WOTR_IsekaiMod#75]
What is TTCCore?

**Comment by Brody1018** [comment]
Tabletop Core. It is another popular mod that makes WotR more like the tabletop version. If you are downloading it, do so on Github. I am pretty sure the author stopped updating the mod on Nexus, but I haven't checked in a while so I could be mistaken.

**Comment by Brody1018** [comment]
https://github.com/Vek17/TabletopTweaks-Core

**Comment by Magdi76** [comment]
Thank you

**Comment by kjk001** [comment]
Actually TT-Base and TT-Reworks are the ones that make it act more like the tabletop version and add new functionaility and rules.

TT-Core itself is a core mod that the developers of the Tabletop Tweaks system provided as a centralized module offering functions and extensions to code in a centralized module so that other developers can use them directly rather than being "inspired" by Tabletop Tweaks in their own code.
Offering such centralized methods should at least in theory allow for code that is easier to bugfix, better compatibility amongst the mods themself, etc.
The idea being that if someone finds a bug in some core method it just hs to be fixed in the core module rather than every one of the three dozen mods that use it.
