### ISSUE TITLE
Issue with Spirit Beacon

### ISSUE THREAD

**Issue by Nerin3** [JohN100x1/WOTR_IsekaiMod#89]
![image](https://user-images.githubusercontent.com/1911661/225395517-7f60d1c8-0bd7-4629-8a41-cddc4901d7ea.png)
![image](https://user-images.githubusercontent.com/1911661/225395719-9f984d4f-20fc-4cc4-bb8c-175fab8dce0b.png)

**Comment by kjk001** [comment]
Yes that is a bug but not in our code.
If you go and check the actual shaman you should have the same problem there, because we don't actually create any of those feats we just copy them over from there.

I will check if I get the same problem and if so try to find the mod that caused it.
Then we know who to report it to.

**Comment by kjk001** [comment]
![image](https://user-images.githubusercontent.com/121681604/225744383-7fbb60e0-065a-4d74-a96b-e041b15eee71.png)
and the culprit is Mystical Mayhem
@Nerin3 want to be the one reporting the bug there?

**Comment by Nerin3** [comment]
Since you've already have screenshots I would appreciate if you reported this instead.

**Comment by JohN100x1** [comment]
Since this issue is unrelated to the mod I will close it for now.
