### ISSUE TITLE
Typos and incorrect grammar fix

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#90]
There are typos and incorrect grammar in the description of some features according to this [user](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=122335125).

> This is not an exhaustive list (and I could be the one wrong here, as my grammar is far from perfect):
> 1. Dual Legacy: ... first[,] ... then 3 years [later,] ... that[,] ... [theives' guild]
> 2. Mythic Class Feature: as well[,] didn't you?
> 3. Ball of Rage: too close[,] aren't you?
> 4. Musical Prodige should be "Prodigy," right?
> 5. Dread Lord: Uhm[,] ... As in the [sic] they... blade [looks]
> 6. Kinetic Knight: Just like all[,] ... [. After all] ... you willingly [chose] to forego ... and instead [chose] to use...
> 7. Kinetic Lord: But you really [love]
> 8. Spellblade: Meh[,]
> 9. Hero of Light: [smiting] your enemies
> 10. Spirit Beacons: [Persons] who[,] [originated] ... Spirit Beacon[,] [have]... (note: used plural form for consistency)
> 11. Chimera: [allow] ... [Chimeras are] constantly
> 12. Isekai Tactician: tactician [who led]
> 13. Supernatural Thief: great power[;] that

**Comment by kjk001** [comment]
actually the Prodige one is not a typo, the rest very likely are correct corrections though, as I will be the first to admit that I am terrible when it comes to commas.
Also some of the descriptions were not by me but just copied from the suggestion, so I am sharing the blame with Nerion and a few others.

The Prodige one was an easter egg, because it is the french version of the Term Prodigy, and we are talking about a musical hero...
